-- ================================================================
-- MIGRATION 003 — MENU: Subcategorias + Campos Extra + Índices + RLS
-- MenusMoz / Locais de Moz
-- ================================================================
-- Adapta as tabelas menu_categories e menu_items já existentes.
-- Cria tabela subcategories (nova camada hierárquica).
-- Hierarquia: menu_categories → subcategories → menu_items
-- ID type: bigint (compatível com restaurants.id existente)
-- ================================================================

-- ── PASSO 2A — Adicionar campos em menu_categories ────────────────
ALTER TABLE public.menu_categories
  ADD COLUMN IF NOT EXISTS order_index integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now();

-- Copiar sort_order → order_index para preservar ordenação
UPDATE public.menu_categories SET order_index = sort_order WHERE order_index = 0 AND sort_order > 0;

-- ── PASSO 2B — Criar tabela subcategories ─────────────────────────
CREATE TABLE IF NOT EXISTS public.subcategories (
  id          bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  category_id bigint NOT NULL REFERENCES public.menu_categories(id) ON DELETE CASCADE,
  name        text NOT NULL,
  order_index integer NOT NULL DEFAULT 0,
  created_at  timestamptz DEFAULT now()
);

-- ── PASSO 2C — Adicionar campos em menu_items ─────────────────────
ALTER TABLE public.menu_items
  ADD COLUMN IF NOT EXISTS subcategory_id bigint REFERENCES public.subcategories(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS is_popular    boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS tags          text[],
  ADD COLUMN IF NOT EXISTS order_index   integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS created_at    timestamptz DEFAULT now();

-- ── PASSO 3 — Índices de performance ──────────────────────────────
CREATE INDEX IF NOT EXISTS idx_menu_categories_restaurant  ON public.menu_categories(restaurant_id);
CREATE INDEX IF NOT EXISTS idx_menu_categories_order       ON public.menu_categories(restaurant_id, order_index);
CREATE INDEX IF NOT EXISTS idx_subcategories_category      ON public.subcategories(category_id);
CREATE INDEX IF NOT EXISTS idx_menu_items_subcategory      ON public.menu_items(subcategory_id);
CREATE INDEX IF NOT EXISTS idx_menu_items_popular          ON public.menu_items(subcategory_id, is_popular) WHERE is_popular = true;
CREATE INDEX IF NOT EXISTS idx_menu_items_available        ON public.menu_items(subcategory_id, is_available) WHERE is_available = true;

-- ── PASSO 4 — RLS em subcategories ────────────────────────────────
-- (menu_categories e menu_items já têm RLS via migration 002)
ALTER TABLE public.subcategories ENABLE ROW LEVEL SECURITY;

CREATE POLICY "subcategories_select_public"
  ON public.subcategories FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.menu_categories mc
      JOIN public.restaurants r ON r.id = mc.restaurant_id
      WHERE mc.id = category_id AND r.is_active = true
    )
  );

CREATE POLICY "subcategories_write_owner"
  ON public.subcategories FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM public.menu_categories mc
      JOIN public.restaurants r ON r.id = mc.restaurant_id
      WHERE mc.id = category_id AND r.owner_id = auth.uid()
    )
  );
