-- ================================================================
-- MIGRATION 004 — HERO SLIDES & BLOG POSTS
-- MenusMoz / Locais de Moz
-- ================================================================
-- Creates the hero_slides and blog_posts tables queried by
-- restaurantService.getHeroSlides() and restaurantService.getBlogPosts().
-- All bilingual fields use _pt / _en suffixes to match frontend mapping.
-- ================================================================

-- ── 1. Hero Slides ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.hero_slides (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title_pt    TEXT NOT NULL,
  title_en    TEXT,
  name_pt     TEXT,
  name_en     TEXT,
  tagline_pt  TEXT,
  tagline_en  TEXT,
  description_pt TEXT,
  description_en TEXT,
  image_url   TEXT NOT NULL,
  button_link TEXT DEFAULT '/',
  is_active   BOOLEAN DEFAULT TRUE,
  sort_order  INTEGER DEFAULT 0,
  created_at  TIMESTAMPTZ DEFAULT NOW(),
  updated_at  TIMESTAMPTZ DEFAULT NOW()
);

-- ── 2. Blog Posts ─────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.blog_posts (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug          TEXT UNIQUE NOT NULL,
  title_pt      TEXT NOT NULL,
  title_en      TEXT,
  excerpt_pt    TEXT,
  excerpt_en    TEXT,
  content_pt    TEXT,
  content_en    TEXT,
  image_url     TEXT,
  author        TEXT,
  category      TEXT,
  is_published  BOOLEAN DEFAULT FALSE,
  published_at  TIMESTAMPTZ DEFAULT NOW(),
  created_at    TIMESTAMPTZ DEFAULT NOW(),
  updated_at    TIMESTAMPTZ DEFAULT NOW()
);

-- ── 3. RLS ────────────────────────────────────────────────────────
ALTER TABLE public.hero_slides ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.blog_posts  ENABLE ROW LEVEL SECURITY;

-- Hero slides: public read for active slides
CREATE POLICY "hero_slides_select_public"
  ON public.hero_slides FOR SELECT
  USING (is_active = true);

-- Hero slides: admin write
CREATE POLICY "hero_slides_admin_all"
  ON public.hero_slides FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE id = auth.uid() AND role = 'admin'
    )
  );

-- Blog posts: public read for published posts
CREATE POLICY "blog_posts_select_public"
  ON public.blog_posts FOR SELECT
  USING (is_published = true);

-- Blog posts: admin write
CREATE POLICY "blog_posts_admin_all"
  ON public.blog_posts FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE id = auth.uid() AND role = 'admin'
    )
  );

-- ── 4. Indexes ────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_hero_slides_active_order
  ON public.hero_slides(is_active, sort_order);

CREATE INDEX IF NOT EXISTS idx_blog_posts_published
  ON public.blog_posts(is_published, published_at DESC);
