-- ================================================================
-- MIGRATION 008 - RESTAURANT MEDIA + STORAGE BUCKET
-- MenusMoz / Locais de Moz
-- ================================================================
-- Adds the media columns already consumed by the frontend and sets up
-- a public Supabase Storage bucket for restaurant assets.
-- ================================================================

-- Restaurants: media columns used by restaurantService + UI
ALTER TABLE public.restaurants
  ADD COLUMN IF NOT EXISTS cover_url      TEXT,
  ADD COLUMN IF NOT EXISTS hero_image_url TEXT,
  ADD COLUMN IF NOT EXISTS logo_url       TEXT,
  ADD COLUMN IF NOT EXISTS gallery        JSONB DEFAULT '[]'::jsonb;

-- Owner applications table used by /proprietarios page
CREATE TABLE IF NOT EXISTS public.owner_applications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_name TEXT NOT NULL,
  email TEXT NOT NULL,
  whatsapp TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.owner_applications ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'owner_applications'
      AND policyname = 'owner_applications_insert_public'
  ) THEN
    CREATE POLICY "owner_applications_insert_public"
      ON public.owner_applications FOR INSERT
      WITH CHECK (true);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'owner_applications'
      AND policyname = 'owner_applications_admin_read'
  ) THEN
    CREATE POLICY "owner_applications_admin_read"
      ON public.owner_applications FOR SELECT
      USING (
        EXISTS (
          SELECT 1 FROM public.profiles
          WHERE id = auth.uid() AND role = 'admin'
        )
      );
  END IF;
END $$;

-- Storage bucket for logos, covers, hero banners, menu photos, etc.
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'restaurant-media',
  'restaurant-media',
  true,
  10485760,
  ARRAY['image/jpeg', 'image/png', 'image/webp', 'image/svg+xml']
)
ON CONFLICT (id) DO UPDATE
SET
  public = EXCLUDED.public,
  file_size_limit = EXCLUDED.file_size_limit,
  allowed_mime_types = EXCLUDED.allowed_mime_types;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'storage'
      AND tablename = 'objects'
      AND policyname = 'restaurant_media_public_read'
  ) THEN
    CREATE POLICY "restaurant_media_public_read"
      ON storage.objects FOR SELECT
      USING (bucket_id = 'restaurant-media');
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'storage'
      AND tablename = 'objects'
      AND policyname = 'restaurant_media_authenticated_upload'
  ) THEN
    CREATE POLICY "restaurant_media_authenticated_upload"
      ON storage.objects FOR INSERT
      TO authenticated
      WITH CHECK (bucket_id = 'restaurant-media');
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'storage'
      AND tablename = 'objects'
      AND policyname = 'restaurant_media_authenticated_update'
  ) THEN
    CREATE POLICY "restaurant_media_authenticated_update"
      ON storage.objects FOR UPDATE
      TO authenticated
      USING (bucket_id = 'restaurant-media')
      WITH CHECK (bucket_id = 'restaurant-media');
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'storage'
      AND tablename = 'objects'
      AND policyname = 'restaurant_media_authenticated_delete'
  ) THEN
    CREATE POLICY "restaurant_media_authenticated_delete"
      ON storage.objects FOR DELETE
      TO authenticated
      USING (bucket_id = 'restaurant-media');
  END IF;
END $$;
