-- ================================================================
-- MIGRATION 010 — MENU CATEGORY IMAGES + CUISINE CATEGORIES TABLE
-- MenusMoz / Locais de Moz
-- ================================================================
-- 1. Adds the per-restaurant menu section image columns consumed by
--    MenuCategories.tsx (menu_food_image, menu_drinks_image,
--    menu_desserts_image).
-- 2. Creates the cuisine_categories table so the CategoryFilter
--    component on the homepage can fetch its images from Supabase.
-- ================================================================

-- ── 1. Restaurant menu section images ────────────────────────────
ALTER TABLE public.restaurants
  ADD COLUMN IF NOT EXISTS menu_food_image      TEXT,
  ADD COLUMN IF NOT EXISTS menu_drinks_image    TEXT,
  ADD COLUMN IF NOT EXISTS menu_desserts_image  TEXT;

-- ── 2. Rich restaurant fields that were in the interface but not DB ─
ALTER TABLE public.restaurants
  ADD COLUMN IF NOT EXISTS story              TEXT,
  ADD COLUMN IF NOT EXISTS dress_code         TEXT,
  ADD COLUMN IF NOT EXISTS parking            TEXT,
  ADD COLUMN IF NOT EXISTS payment_methods    TEXT[],
  ADD COLUMN IF NOT EXISTS accessibility      TEXT[],
  ADD COLUMN IF NOT EXISTS ambiance_tags      TEXT[],
  ADD COLUMN IF NOT EXISTS awards             JSONB  DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS signature_dishes   JSONB  DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS logo_url           TEXT,
  ADD COLUMN IF NOT EXISTS website            TEXT,
  ADD COLUMN IF NOT EXISTS whatsapp           TEXT,
  ADD COLUMN IF NOT EXISTS bio                TEXT,
  ADD COLUMN IF NOT EXISTS latitude           NUMERIC,
  ADD COLUMN IF NOT EXISTS longitude          NUMERIC,
  ADD COLUMN IF NOT EXISTS location           TEXT;

-- ── 3. Cuisine Categories table (for homepage category carousel) ──
CREATE TABLE IF NOT EXISTS public.cuisine_categories (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        TEXT NOT NULL,
  slug        TEXT UNIQUE NOT NULL,
  image_url   TEXT,
  sort_order  INTEGER DEFAULT 0,
  is_active   BOOLEAN DEFAULT TRUE,
  created_at  TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.cuisine_categories ENABLE ROW LEVEL SECURITY;

-- Public read for active categories
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'cuisine_categories'
      AND policyname = 'cuisine_categories_select_public'
  ) THEN
    CREATE POLICY "cuisine_categories_select_public"
      ON public.cuisine_categories FOR SELECT
      USING (is_active = true);
  END IF;
END $$;

-- Admin write
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'cuisine_categories'
      AND policyname = 'cuisine_categories_admin_all'
  ) THEN
    CREATE POLICY "cuisine_categories_admin_all"
      ON public.cuisine_categories FOR ALL
      USING (
        EXISTS (
          SELECT 1 FROM public.profiles
          WHERE id = auth.uid() AND role = 'admin'
        )
      );
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_cuisine_categories_active_order
  ON public.cuisine_categories (is_active, sort_order);

-- ── 4. Seed default cuisine categories ───────────────────────────
-- Insert default rows only if the table is empty so re-runs are safe.
INSERT INTO public.cuisine_categories (name, slug, image_url, sort_order)
SELECT * FROM (VALUES
  ('Mariscos',    'mariscos',    'https://images.unsplash.com/photo-1615141982883-c7ad0e69fd62?w=800&h=1200&fit=crop', 1),
  ('Portuguesa',  'portuguesa',  'https://images.unsplash.com/photo-1534080564583-6be75777b700?w=800&h=1200&fit=crop', 2),
  ('Pastelaria',  'pastelaria',  'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800&h=1200&fit=crop', 3),
  ('Street Food', 'street-food', 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&h=1200&fit=crop', 4),
  ('Moçambicana', 'mocambicana', 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=800&h=1200&fit=crop', 5),
  ('Grelhados',   'grelhados',   'https://images.unsplash.com/photo-1544025162-d76694265947?w=800&h=1200&fit=crop', 6)
) AS v(name, slug, image_url, sort_order)
WHERE NOT EXISTS (SELECT 1 FROM public.cuisine_categories LIMIT 1);
